version: '3'
services:
  nginx:
   container_name: iamdoggy_nginx
   image: nginx:1.13
   restart: always
   ports:
     - 80:80
     - 443:443
   volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
     - app
 
  management_mysql:
   container_name: management_mysql
   image: mysql/mysql-server:5.7
   environment:
     - MYSQL_DATABASE=management
     - MYSQL_USER=iamdoggy
     - MYSQL_PASSWORD=iamdoggy
     - MYSQL_ROOT_PASSWORD=fytech
     - MYSQL_ROOT_HOST=%
   restart: always
  
  doggy_mysql:
   container_name: doggy_mysql
   image: mysql/mysql-server:5.7
   environment:
     - MYSQL_DATABASE=doggy
     - MYSQL_USER=iamdoggy
     - MYSQL_PASSWORD=iamdoggy
     - MYSQL_ROOT_PASSWORD=fytech
     - MYSQL_ROOT_HOST=%
   restart: always
   
  app:
    container_name: app
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - 8080
    depends_on:
      - management_mysql
      - doggy_mysql